export default ({
    addLabel,
    allowEmpty,
    basePath,
    cellClassName,
    className,
    formClassName,
    headerClassName,
    isFullWidthVisible,
    label,
    linkToResource,
    linkType,
    locale,
    record,
    resource,
    showFullWidthTableRow,
    showRowOverlay,
    sortable,
    source,
    textAlign,
    translateChoice,
    ...rest
}) => rest;
